"""empty message

Revision ID: d28c2ea77efa
Revises: 
Create Date: 2017-10-03 08:26:15.607857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28c2ea77efa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(length=200), nullable=True),
    sa.Column('original_language', sa.String(length=32), nullable=True),
    sa.Column('translated_text', sa.Text(length=200), nullable=True),
    sa.Column('translated_language', sa.String(length=32), nullable=True),
    sa.Column('shortcut', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    # ### end Alembic commands ###
