"""Adding shortcut field to translation model.

Revision ID: 41a9af063665
Revises: dce7aa3c4a86
Create Date: 2017-07-24 14:21:38.941450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a9af063665'
down_revision = 'dce7aa3c4a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('shortcut', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation', 'shortcut')
    # ### end Alembic commands ###
