"""Added original language and translation language to translation model.

Revision ID: dce7aa3c4a86
Revises: bddf843585f2
Create Date: 2017-07-24 12:50:02.017782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce7aa3c4a86'
down_revision = 'bddf843585f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('original_language', sa.String(length=32), nullable=True))
    op.add_column('translation', sa.Column('translated_language', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation', 'translated_language')
    op.drop_column('translation', 'original_language')
    # ### end Alembic commands ###
